# Generated by Django 4.0.1 on 2022-02-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomm.category'),
        ),
    ]
